deploy:
  runs-on: self-hosted  # still correct
  needs: build

  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up SSH
      shell: pwsh
      run: |
        mkdir $HOME\.ssh
        Set-Content -Path $HOME\.ssh\id_rsa -Value "${{ secrets.DEPLOY_KEY }}" -NoNewline
        icacls $HOME\.ssh\id_rsa /inheritance:r
        icacls $HOME\.ssh\id_rsa /grant:r "$($env:USERNAME):(R)"
        ssh-keyscan 192.168.1.24 >> $HOME\.ssh\known_hosts

    - name: Deploy to server
      shell: pwsh
      run: |
        ssh -i $HOME\.ssh\id_rsa -o StrictHostKeyChecking=no poorani@192.168.1.24 "bash -x /home/ubuntu/deploy.sh"
