name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main   # Trigger on PR creation/updates to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runner environment, you can also use other OS types

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2  # This action checks out your code from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Setup the Node.js environment (skip if not applicable)

      - name: Install dependencies
        run: |
          npm install  # Modify for your dependency manager (e.g., pip, gradle)

      - name: Run tests
        run: |
          npm test  # Add your backend test commands here (e.g., `npm run test`, `pytest`)

  deploy:
    runs-on: ubuntu-latest
    needs: build   # This ensures deploy runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@123.45.67.89 'bash /home/ubuntu/deploy.sh'
